### ISSUE TITLE
Guide: Innsbruck

### ISSUE THREAD

**Issue by Sgoettschkes** [agileaddicts/pogo.travel#39]
## Basic information

* Writer: Cyrille / Sebastian
* Proof-Reader: Sebastian
* Image gatherer: Sebastian
* Agreed timeframe: 10.05.2017

## Links

* Google Doc
* Staging guide
* Prod guide

## ToDos

- [ ] Write text
- [ ] Prepare header image (Find, crop and optimize)
- [ ] Prepare header copyright
- [ ] Prepare content images (Find, crop and optimize)
- [ ] Proof read
- [ ] Put on staging
- [ ] Final check
  - [ ] Desktop
  - [ ] Tablet
  - [ ] Mobile
- [ ] Put on production
